vars { d2-config.pad: 16 }
direction: right
d: 🎚️ Dimmer {style.border-radius: 8 }
t: "room/light\n(retained)"
l: 💡 Light { style.border-radius: 8 }
d -> t -> l { style.animated: true }
t -> d { style.animated: true } 
